branch-defaults:
  default:
    environment: PROD-TODO-BACKEND
    group_suffix: null
deploy:
  artifact: build/libs/demo-0.0.1-SNAPSHOT.jar
environment-defaults:
  PROD-TODO-BACKEND:
    branch: null
    repository: null
global:
  application_name: TodoApplication-backend
  branch: null
  default_ec2_keyname: null
  default_platform: Corretto 17 running on 64bit Amazon Linux 2023
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
